[package]
name = "spectrogram"
version = "0.1.0"
edition = "2021"
authors = ["Carlo Dell'Acqua <carlo.dellacqua97@gmail.com>"]
license = "MIT"
repository = "https://github.com/cdellacqua/spectrogram.rs"

[profile.release]
debug = true

[dependencies]
anyhow = "1.0.86"
dotenv-flow = "0.16.2"
itertools = "0.13.0"
rustfft = "6.2.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
wav = "1.0.1"
nalgebra = "0.33.2"
macroquad = "0.4.13"

audio = { git = "https://github.com/cdellacqua/miscellaneous_libs.rs.git", rev = "46bc05afd9bd71f8a75295b7e24310a55afa8705", features = ["analysis", "input"] }
mutex_ext = { git = "https://github.com/cdellacqua/miscellaneous_libs.rs.git", rev = "46bc05afd9bd71f8a75295b7e24310a55afa8705" }
math_utils = { git = "https://github.com/cdellacqua/miscellaneous_libs.rs.git", rev = "46bc05afd9bd71f8a75295b7e24310a55afa8705" }
ringbuffer = { git = "https://github.com/cdellacqua/ringbuffer.rs.git", rev = "d7bcb7a1817f8c841605025a7f00441c499e547c" }

# [patch."https://github.com/cdellacqua/miscellaneous_libs.rs.git"]
# audio = { path = "../miscellaneous_libs.rs/audio.rs", features = ["full"] }
# math_utils = { path = "../miscellaneous_libs.rs/math_utils.rs" }
# mutex_ext = { path = "../miscellaneous_libs.rs/mutex_ext.rs" }
